# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0136a523017d2018b01526946a6aac4d"
name = "demo-gm-reward-app"
handle = "demo-gm-reward-app-1"
application_url = "https://waste-upper-lanes-fr.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "hn-checkout-extention-demo-1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,write_orders,write_products"

[auth]
redirect_urls = [
  "https://waste-upper-lanes-fr.trycloudflare.com/auth/callback",
  "https://waste-upper-lanes-fr.trycloudflare.com/auth/shopify/callback",
  "https://waste-upper-lanes-fr.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
